### ISSUE TITLE
Error when installing psycopg2-2.8.6

### ISSUE THREAD

**Issue by yqchau** [HackSoftware/Django-React-GoogleOauth2-Example#4]
Greetings,

<img width="728" alt="Screenshot 2021-07-28 at 1 00 41 AM" src="https://user-images.githubusercontent.com/65069848/127196683-375a92f1-2cdb-45bb-be0e-7d048bbc2d7c.png">
I am facing this trouble when creating an env(python3.9.5) and installing requirements.txt. Would appreciate it if you can help me out !

**Comment by EudinoDev** [comment]
Hello guys, I need your help to run this demo app in local machine on windows, please ! thanks in advance for your response

**Comment by RadoRado** [comment]
@cyuanqi920 Hello, this looks like a local issue on your end.

I'd suggest looking here - https://www.hacksoft.io/blog/github-actions-in-action-setting-up-django-and-postgres#psycopg2-dependencies - the Postgres section:

There are additional binaries that you need to install.

Try with:

```
sudo apt-get install libpq-dev
```

In addition, make sure to read this - https://www.psycopg.org/docs/install.html#build-prerequisites

**Comment by RadoRado** [comment]
@EudinoDev :wave: 

Sorry, we cannot help you with Windows, since we don't use Windows :(

I suppose you have issues with either Postgres or Python. If you google around, you'll find plenty of examples for how to run Django on Windows.
